### PR TITLE
Update Emoji list

### PR DESCRIPTION
**Pull request by dstranz**
I think it's worth to update emoji list, there are some missing emojis like 🥳 .

### CODE REVIEW

**Comment by onmyway133** [comment]
@dstranz Hi, thanks for the PR 👍

**Comment by dstranz** [comment]
@onmyway133 It will be good to add new version in https://github.com/onmyway133/Smile/releases to easier use with SPM.

**Comment by onmyway133** [comment]
@dstranz Hi, I will make new release soon

**Comment by kiliankoe** [comment]
Thanks for the emoji update! 

I am however confused why the categories where changed. Afaict the canonical list is
 - 😃 Smileys & People
 - 🐻 Animals & Nature
 - 🍔 Food & Drink
 - ⚽ Activity
 - 🌇 Travel & Places
 - 💡 Objects
 - 🔣 Symbols
 - 🎌 Flags

(based on [Emojipedia](https://emojipedia.org) and from what I can see on Apple platforms). 

Would it not make sense to stick with these names and groupings instead of creating new names and a "People & Body" category?

**Comment by kiliankoe** [comment]
Ah, I see that this is already how GitHub chose to sort things in [github.com/github/gemoji](https://github.com/github/gemoji).

In that case I don't know what to believe 😅

**Pull request merged**
