### PR TITLE
Add SwiftPM package manifest

### PR DESCRIPTION
**Pull request by kiliankoe**
Huge thanks for the library! ❤️

This adds support for using SwiftPM to depend on Smile.

### CODE REVIEW

**Comment by onmyway133** [comment]
@kiliankoe Hi thanks for the PR, seem like everyone 's moving to SPM now

**Comment by kiliankoe** [comment]
A new release with these changes would be grand as well, unfortunately SwiftPM relies on the manifest being present in a checkout, so it's currently only possible to depend on master. I however don't know if the other unreleased changes on master are ready for a release, just wanted to point that out 😊

**Comment by onmyway133** [comment]
@kiliankoe Hi, I just release https://github.com/onmyway133/Smile/releases/tag/2.1.0 can you check if it works for you?

**Comment by kiliankoe** [comment]
Works great, thank you!

**Pull request merged**
